[08/29/2019 22:10:04] [e(0)] core: DB.connect threw an exception: bad URI(is not URI?): <%= ENV['DATABASE_URL'] %>
[08/29/2019 22:10:05] [e(0)] core: DB.connect threw an exception: ActiveRecord::ConnectionNotEstablished
[08/29/2019 22:10:05] [e(0)] core: Failed to connect to the database: ActiveRecord::ConnectionNotEstablished
[08/29/2019 22:10:05] [d(0)] core: Created user based module store
[08/29/2019 22:10:10] [e(0)] core: Unable to load module /usr/src/metasploit-framework/modules/auxiliary/gather/office365userenum.py, unknown module type
[08/29/2019 22:29:48] [e(0)] core: DB.connect threw an exception: bad URI(is not URI?): <%= ENV['DATABASE_URL'] %>
[08/29/2019 22:29:48] [e(0)] core: DB.connect threw an exception: ActiveRecord::ConnectionNotEstablished
[08/29/2019 22:29:48] [e(0)] core: Failed to connect to the database: ActiveRecord::ConnectionNotEstablished
[08/29/2019 22:29:52] [e(0)] core: Unable to load module /usr/src/metasploit-framework/modules/auxiliary/gather/office365userenum.py, unknown module type
[08/29/2019 22:31:51] [e(0)] core: Error loading plugin ./METASTARTUP/msfconsole.rc: cannot load such file -- ./METASTARTUP/msfconsole.rc

/usr/local/bundle/gems/backports-3.15.0/lib/backports/std_lib.rb:9:in `require'
/usr/local/bundle/gems/backports-3.15.0/lib/backports/std_lib.rb:9:in `require_with_backports'
/usr/local/bundle/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `block in require'
/usr/local/bundle/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/local/bundle/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `require'
/usr/src/metasploit-framework/lib/msf/core/plugin_manager.rb:52:in `load'
/usr/src/metasploit-framework/lib/msf/base/simple/framework.rb:36:in `load'
/usr/src/metasploit-framework/lib/msf/ui/console/command_dispatcher/core.rb:753:in `load_plugin'
/usr/src/metasploit-framework/lib/msf/ui/console/command_dispatcher/core.rb:775:in `cmd_load'
/usr/src/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:523:in `run_command'
/usr/src/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:474:in `block in run_single'
/usr/src/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:468:in `each'
/usr/src/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:468:in `run_single'
/usr/src/metasploit-framework/lib/rex/ui/text/shell.rb:151:in `run'
/usr/src/metasploit-framework/lib/metasploit/framework/command/console.rb:48:in `start'
/usr/src/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in `start'
./msfconsole:49:in `<main>'
[08/29/2019 22:32:00] [e(0)] core: Error loading plugin METASTARTUP/msfconsole.rc: cannot load such file -- METASTARTUP/msfconsole.rc

/usr/local/bundle/gems/backports-3.15.0/lib/backports/std_lib.rb:9:in `require'
/usr/local/bundle/gems/backports-3.15.0/lib/backports/std_lib.rb:9:in `require_with_backports'
/usr/local/bundle/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `block in require'
/usr/local/bundle/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/local/bundle/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `require'
/usr/src/metasploit-framework/lib/msf/core/plugin_manager.rb:52:in `load'
/usr/src/metasploit-framework/lib/msf/base/simple/framework.rb:36:in `load'
/usr/src/metasploit-framework/lib/msf/ui/console/command_dispatcher/core.rb:753:in `load_plugin'
/usr/src/metasploit-framework/lib/msf/ui/console/command_dispatcher/core.rb:775:in `cmd_load'
/usr/src/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:523:in `run_command'
/usr/src/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:474:in `block in run_single'
/usr/src/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:468:in `each'
/usr/src/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:468:in `run_single'
/usr/src/metasploit-framework/lib/rex/ui/text/shell.rb:151:in `run'
/usr/src/metasploit-framework/lib/metasploit/framework/command/console.rb:48:in `start'
/usr/src/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in `start'
./msfconsole:49:in `<main>'
[08/29/2019 22:34:37] [e(0)] core: DB.connect threw an exception: bad URI(is not URI?): <%= ENV['DATABASE_URL'] %>
[08/29/2019 22:34:37] [e(0)] core: DB.connect threw an exception: ActiveRecord::ConnectionNotEstablished
[08/29/2019 22:34:37] [e(0)] core: Failed to connect to the database: ActiveRecord::ConnectionNotEstablished
[08/29/2019 22:34:41] [e(0)] core: Unable to load module /usr/src/metasploit-framework/modules/auxiliary/gather/office365userenum.py, unknown module type
[08/30/2019 03:49:17] [e(0)] core: DB.connect threw an exception: bad URI(is not URI?): <%= ENV['DATABASE_URL'] %>
[08/30/2019 03:49:17] [e(0)] core: DB.connect threw an exception: ActiveRecord::ConnectionNotEstablished
[08/30/2019 03:49:17] [e(0)] core: Failed to connect to the database: ActiveRecord::ConnectionNotEstablished
[08/30/2019 03:49:21] [e(0)] core: Unable to load module /usr/src/metasploit-framework/modules/auxiliary/gather/office365userenum.py, unknown module type
[08/30/2019 03:52:55] [e(0)] core: DB.connect threw an exception: bad URI(is not URI?): <%= ENV['DATABASE_URL'] %>
[08/30/2019 03:52:55] [e(0)] core: DB.connect threw an exception: ActiveRecord::ConnectionNotEstablished
[08/30/2019 03:52:55] [e(0)] core: Failed to connect to the database: ActiveRecord::ConnectionNotEstablished
[08/30/2019 03:53:00] [e(0)] core: Unable to load module /usr/src/metasploit-framework/modules/auxiliary/gather/office365userenum.py, unknown module type
[08/30/2019 03:54:22] [e(0)] core: DB.connect threw an exception: bad URI(is not URI?): <%= ENV['DATABASE_URL'] %>
[08/30/2019 03:54:22] [e(0)] core: DB.connect threw an exception: ActiveRecord::ConnectionNotEstablished
[08/30/2019 03:54:22] [e(0)] core: Failed to connect to the database: ActiveRecord::ConnectionNotEstablished
[08/30/2019 03:54:26] [e(0)] core: Unable to load module /usr/src/metasploit-framework/modules/auxiliary/gather/office365userenum.py, unknown module type
[08/30/2019 03:58:50] [e(0)] core: Failed to connect to the database: No database YAML file
[08/30/2019 03:58:55] [e(0)] core: Unable to load module /usr/src/metasploit-framework/modules/auxiliary/gather/office365userenum.py, unknown module type
[08/30/2019 03:58:55] [i(0)] core: Database doesn't exist "msf?pool=200&timeout=5", attempting to create it.
[08/30/2019 04:10:03] [e(0)] core: DB.connect threw an exception: bad URI(is not URI?): <%= ENV['DATABASE_URL'] %>
[08/30/2019 04:10:03] [e(0)] core: DB.connect threw an exception: ActiveRecord::ConnectionNotEstablished
[08/30/2019 04:10:03] [e(0)] core: Failed to connect to the database: ActiveRecord::ConnectionNotEstablished
[08/30/2019 04:10:08] [e(0)] core: Unable to load module /usr/src/metasploit-framework/modules/auxiliary/gather/office365userenum.py, unknown module type
[08/30/2019 04:11:26] [e(0)] core: DB.connect threw an exception: bad URI(is not URI?): <%= ENV['DATABASE_URL'] %>
[08/30/2019 04:11:26] [e(0)] core: DB.connect threw an exception: ActiveRecord::ConnectionNotEstablished
[08/30/2019 04:11:26] [e(0)] core: Failed to connect to the database: ActiveRecord::ConnectionNotEstablished
[08/30/2019 04:11:31] [e(0)] core: Unable to load module /usr/src/metasploit-framework/modules/auxiliary/gather/office365userenum.py, unknown module type
[08/30/2019 04:13:45] [e(0)] core: DB.connect threw an exception: bad URI(is not URI?): <%= ENV['DATABASE_URL'] %>
[08/30/2019 04:13:45] [e(0)] core: DB.connect threw an exception: ActiveRecord::ConnectionNotEstablished
[08/30/2019 04:13:45] [e(0)] core: Failed to connect to the database: ActiveRecord::ConnectionNotEstablished
[08/30/2019 04:13:50] [e(0)] core: Unable to load module /usr/src/metasploit-framework/modules/auxiliary/gather/office365userenum.py, unknown module type
[08/30/2019 04:15:53] [e(0)] core: DB.connect threw an exception: bad URI(is not URI?): <%= ENV['DATABASE_URL'] %>
[08/30/2019 04:15:53] [e(0)] core: DB.connect threw an exception: ActiveRecord::ConnectionNotEstablished
[08/30/2019 04:15:53] [e(0)] core: Failed to connect to the database: ActiveRecord::ConnectionNotEstablished
[08/30/2019 04:15:57] [e(0)] core: Unable to load module /usr/src/metasploit-framework/modules/auxiliary/gather/office365userenum.py, unknown module type
[08/30/2019 04:17:40] [e(0)] core: DB.connect threw an exception: bad URI(is not URI?): <%= ENV['DATABASE_URL'] %>
[08/30/2019 04:17:40] [e(0)] core: DB.connect threw an exception: ActiveRecord::ConnectionNotEstablished
[08/30/2019 04:17:40] [e(0)] core: Failed to connect to the database: ActiveRecord::ConnectionNotEstablished
[08/30/2019 04:17:44] [e(0)] core: Unable to load module /usr/src/metasploit-framework/modules/auxiliary/gather/office365userenum.py, unknown module type
[08/30/2019 04:31:08] [e(0)] core: DB.connect threw an exception: bad URI(is not URI?): <%= ENV['DATABASE_URL'] %>
[08/30/2019 04:31:08] [e(0)] core: DB.connect threw an exception: ActiveRecord::ConnectionNotEstablished
[08/30/2019 04:31:08] [e(0)] core: Failed to connect to the database: ActiveRecord::ConnectionNotEstablished
[08/30/2019 04:31:13] [e(0)] core: Unable to load module /usr/src/metasploit-framework/modules/auxiliary/gather/office365userenum.py, unknown module type
[08/30/2019 04:56:16] [e(0)] core: DB.connect threw an exception: bad URI(is not URI?): <%= ENV['DATABASE_URL'] %>
[08/30/2019 04:56:16] [e(0)] core: DB.connect threw an exception: ActiveRecord::ConnectionNotEstablished
[08/30/2019 04:56:16] [e(0)] core: Failed to connect to the database: ActiveRecord::ConnectionNotEstablished
[08/30/2019 04:56:57] [e(0)] core: DB.connect threw an exception: bad URI(is not URI?): <%= ENV['DATABASE_URL'] %>
[08/30/2019 04:56:57] [e(0)] core: DB.connect threw an exception: ActiveRecord::ConnectionNotEstablished
[08/30/2019 04:56:57] [e(0)] core: Failed to connect to the database: ActiveRecord::ConnectionNotEstablished
[08/30/2019 04:57:02] [e(0)] core: Unable to load module /usr/src/metasploit-framework/modules/auxiliary/gather/office365userenum.py, unknown module type
[08/30/2019 04:57:57] [e(0)] core: Failed to connect to the database: No database YAML file
[08/30/2019 04:58:02] [e(0)] core: Unable to load module /usr/src/metasploit-framework/modules/auxiliary/gather/office365userenum.py, unknown module type
[08/30/2019 04:58:26] [e(0)] core: DB.connect threw an exception: bad URI(is not URI?): <%= ENV['DATABASE_URL'] %>
[08/30/2019 04:58:26] [e(0)] core: DB.connect threw an exception: ActiveRecord::ConnectionNotEstablished
[08/30/2019 04:58:26] [e(0)] core: Failed to connect to the database: ActiveRecord::ConnectionNotEstablished
[08/30/2019 04:58:31] [e(0)] core: Unable to load module /usr/src/metasploit-framework/modules/auxiliary/gather/office365userenum.py, unknown module type
[08/30/2019 05:42:54] [e(0)] core: DB.connect threw an exception: bad URI(is not URI?): <%= ENV['DATABASE_URL'] %>
[08/30/2019 05:42:54] [e(0)] core: DB.connect threw an exception: ActiveRecord::ConnectionNotEstablished
[08/30/2019 05:42:54] [e(0)] core: Failed to connect to the database: ActiveRecord::ConnectionNotEstablished
[08/30/2019 05:43:00] [e(0)] core: Unable to load module /usr/src/metasploit-framework/modules/auxiliary/gather/office365userenum.py, unknown module type
[08/30/2019 05:45:30] [e(0)] core: DB.connect threw an exception: bad URI(is not URI?): <%= ENV['DATABASE_URL'] %>
[08/30/2019 05:45:30] [e(0)] core: DB.connect threw an exception: ActiveRecord::ConnectionNotEstablished
[08/30/2019 05:45:30] [e(0)] core: Failed to connect to the database: ActiveRecord::ConnectionNotEstablished
[08/30/2019 05:45:35] [e(0)] core: Unable to load module /usr/src/metasploit-framework/modules/auxiliary/gather/office365userenum.py, unknown module type
[08/30/2019 05:47:54] [e(0)] core: DB.connect threw an exception: bad URI(is not URI?): <%= ENV['DATABASE_URL'] %>
[08/30/2019 05:47:54] [e(0)] core: DB.connect threw an exception: ActiveRecord::ConnectionNotEstablished
[08/30/2019 05:47:54] [e(0)] core: Failed to connect to the database: ActiveRecord::ConnectionNotEstablished
[08/30/2019 05:47:58] [e(0)] core: Unable to load module /usr/src/metasploit-framework/modules/auxiliary/gather/office365userenum.py, unknown module type
[08/30/2019 06:02:41] [e(0)] core: DB.connect threw an exception: bad URI(is not URI?): <%= ENV['DATABASE_URL'] %>
[08/30/2019 06:02:41] [e(0)] core: DB.connect threw an exception: ActiveRecord::ConnectionNotEstablished
[08/30/2019 06:02:41] [e(0)] core: Failed to connect to the database: ActiveRecord::ConnectionNotEstablished
[08/30/2019 06:02:46] [e(0)] core: Unable to load module /usr/src/metasploit-framework/modules/auxiliary/gather/office365userenum.py, unknown module type
[08/30/2019 06:04:28] [e(0)] core: DB.connect threw an exception: bad URI(is not URI?): <%= ENV['DATABASE_URL'] %>
[08/30/2019 06:04:28] [e(0)] core: DB.connect threw an exception: ActiveRecord::ConnectionNotEstablished
[08/30/2019 06:04:28] [e(0)] core: Failed to connect to the database: ActiveRecord::ConnectionNotEstablished
[08/30/2019 06:04:34] [e(0)] core: Unable to load module /usr/src/metasploit-framework/modules/auxiliary/gather/office365userenum.py, unknown module type
[08/30/2019 06:08:05] [e(0)] core: DB.connect threw an exception: bad URI(is not URI?): <%= ENV['DATABASE_URL'] %>
[08/30/2019 06:08:05] [e(0)] core: DB.connect threw an exception: ActiveRecord::ConnectionNotEstablished
[08/30/2019 06:08:05] [e(0)] core: Failed to connect to the database: ActiveRecord::ConnectionNotEstablished
[08/30/2019 06:08:14] [e(0)] core: Unable to load module /usr/src/metasploit-framework/modules/auxiliary/gather/office365userenum.py, unknown module type
[08/30/2019 06:11:06] [e(0)] core: DB.connect threw an exception: bad URI(is not URI?): <%= ENV['DATABASE_URL'] %>
[08/30/2019 06:11:06] [e(0)] core: DB.connect threw an exception: ActiveRecord::ConnectionNotEstablished
[08/30/2019 06:11:06] [e(0)] core: Failed to connect to the database: ActiveRecord::ConnectionNotEstablished
[08/30/2019 06:11:10] [e(0)] core: Unable to load module /usr/src/metasploit-framework/modules/auxiliary/gather/office365userenum.py, unknown module type
[08/30/2019 06:18:45] [e(0)] core: DB.connect threw an exception: bad URI(is not URI?): <%= ENV['DATABASE_URL'] %>
[08/30/2019 06:18:45] [e(0)] core: DB.connect threw an exception: ActiveRecord::ConnectionNotEstablished
[08/30/2019 06:18:45] [e(0)] core: Failed to connect to the database: ActiveRecord::ConnectionNotEstablished
[08/30/2019 06:18:50] [e(0)] core: Unable to load module /usr/src/metasploit-framework/modules/auxiliary/gather/office365userenum.py, unknown module type
